name: Motion_env
dependencies:
  - python=3.8
  - psycopg2
  - pip
  - pip:
      - Django==3.1.2
      - djangorestframework==3.12.1
      - djangorestframework-simplejwt==4.4.0
      - gunicorn
      - flake8