# Generated by Django 3.1.2 on 2020-10-22 16:00

from django.db import migrations, models
import django.db.models.deletion
import images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0004_auto_20201018_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.ImageField(blank=True, null=True, upload_to=images.models.user_directory_path)),
                ('post_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_image_post', to='posts.post')),
            ],
        ),
    ]
